//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock.Modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvisionnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public approvisionnement()
        {
            this.venteProduit = new HashSet<venteProduit>();
        }
    
        public int idApprovisionnement { get; set; }
        public int idProduit { get; set; }
        public System.DateTime dateApprovisionnent { get; set; }
        public System.DateTime dateExpiration { get; set; }
        public double quantite { get; set; }
        public double prixUnitaire { get; set; }
    
        public virtual produit produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venteProduit> venteProduit { get; set; }
    }
}
