//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock.Modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class facture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facture()
        {
            this.venteProduit = new HashSet<venteProduit>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> idLivraison { get; set; }
        public int idUtilisateur { get; set; }
    
        public virtual livraison livraison { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venteProduit> venteProduit { get; set; }
    }
}
