//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock.Modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class venteProduit
    {
        public int idFacture { get; set; }
        public int idApprivisionnement { get; set; }
        public double quantite { get; set; }
    
        public virtual approvisionnement approvisionnement { get; set; }
        public virtual facture facture { get; set; }
    }
}
